<a href="https://colab.research.google.com/github/cleo-bs/Airbnb_RJ/blob/main/Teste.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [132]:
import pandas as pd

df = pd.read_csv(r'netflix.csv')

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8787 entries, 0 to 8789
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8787 non-null   object
 1   type          8787 non-null   object
 2   title         8787 non-null   object
 3   country       8787 non-null   object
 4   date_added    8773 non-null   datetime64[ns]
 5   release_year  8787 non-null   datetime64[ns]
 6   rating        8787 non-null   object
 7   duration      8787 non-null   object
 8   listed_in     8787 non-null   object
 9   Listed 1      8787 non-null   object
 10  Listed 2      6775 non-null   object
 11  Listed 3      3725 non-null   object
dtypes: datetime64[ns](2), object(10)
memory usage: 892.4+ KB

In [134]:
df['date_added'] = pd.to_datetime(df['date_added'], format = '%m/%d/%Y', errors = 'coerce')

In [135]:
df['release_year'] = pd.to_datetime(df['release_year'], format = '%Y', errors = 'coerce')

In [111]:
# shape, tipos, nulls, duplicados.
def info_gerais(df):
  print(f'QTD Linhas Dataset: {df.shape[0]}')
  print(f'QTD Colunas Dataset: {df.shape[1]}\n')

  for i in df.columns:
    print(f'Coluna {i}\n')
    print(f'QTD Nulos: {df[i].isnull().sum()}')
    print(f'% Nulos: {df[i].isnull().sum()/len(df)}\n')
    print(f'QTD Duplicados: {df[i].duplicated().sum()}\n')
    print(f'Quantidade por categoria: {df[i].value_counts()}\n')
    print(f'Quantidade por categoria: {df[i].value_counts()/len(df)*100}\n')
    print(f'Valores distintos: {df[i].nunique()}\n')

In [84]:
# Vê todos os títulos duplicados
df[df['title'].duplicated(keep=False)].sort_values('title')

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,2019-03-29,2019-01-01,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,2019-03-29,2019-01-01,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,2018-10-10,2018-01-01,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,2018-10-10,2018-01-01,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Not Given,Pakistan,2019-03-20,2018-01-01,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Not Given,Pakistan,2019-03-20,2018-01-01,TV-14,1 Season,"International TV Shows, TV Dramas"

In [136]:
info_gerais(df)
#drop director
#

QTD Linhas Dataset: 8790
QTD Colunas Dataset: 10

Coluna show_id

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 0

Quantidade por categoria: show_id
s8786    1
s1       1
s3       1
s6       1
s14      1
        ..
s941     1
s940     1
s13      1
s939     1
s10      1
Name: count, Length: 8790, dtype: int64

Quantidade por categoria: show_id
s8786    0.011377
s1       0.011377
s3       0.011377
s6       0.011377
s14      0.011377
           ...
s941     0.011377
s940     0.011377
s13      0.011377
s939     0.011377
s10      0.011377
Name: count, Length: 8790, dtype: float64

Valores distintos: 8790

Coluna type

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 8788

Quantidade por categoria: type
Movie      6126
TV Show    2664
Name: count, dtype: int64

Quantidade por categoria: type
Movie      69.692833
TV Show    30.307167
Name: count, dtype: float64

Valores distintos: 2

Coluna title

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 3

Quantidade por categoria: title
9-Feb                                2
15-Aug                               2
22-Jul                               2
Septiembre, un llanto en silencio    1
Set Up                               1
                                    ..
Sei                                  1
Superlopez                           1
Oversize Cops                        1
Mirage                               1
The Highwaymen                       1
Name: count, Length: 8787, dtype: int64

Quantidade por categoria: title
9-Feb                                0.022753
15-Aug                               0.022753
22-Jul                               0.022753
Septiembre, un llanto en silencio    0.011377
Set Up                               0.011377
                                       ...
Sei                                  0.011377
Superlopez                           0.011377
Oversize Cops                        0.011377
Mirage                               0.011377
The Highwaymen                       0.011377
Name: count, Length: 8787, dtype: float64

Valores distintos: 8787

Coluna director

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 4262

Quantidade por categoria: director
Not Given                 2588
Rajiv Chilaka               20
Alastair Fothergill         18
Raúl Campos, Jan Suter      18
Marcus Raboy                16
                          ...
Mark Risley                  1
Kirati Nakintanon            1
Christian De Vita            1
Abu Bakr Shawky              1
N. Chandra                   1
Name: count, Length: 4528, dtype: int64

Quantidade por categoria: director
Not Given                 29.442548
Rajiv Chilaka              0.227531
Alastair Fothergill        0.204778
Raúl Campos, Jan Suter     0.204778
Marcus Raboy               0.182025
                            ...
Mark Risley                0.011377
Kirati Nakintanon          0.011377
Christian De Vita          0.011377
Abu Bakr Shawky            0.011377
N. Chandra                 0.011377
Name: count, Length: 4528, dtype: float64

Valores distintos: 4528

Coluna country

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 8704

Quantidade por categoria: country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
                  ...
Luxembourg           1
Senegal              1
Belarus              1
Puerto Rico          1
Cyprus               1
Name: count, Length: 86, dtype: int64

Quantidade por categoria: country
United States     36.860068
India             12.025028
United Kingdom     7.258248
Pakistan           4.789534
Not Given          3.265074
                    ...
Luxembourg         0.011377
Senegal            0.011377
Belarus            0.011377
Puerto Rico        0.011377
Cyprus             0.011377
Name: count, Length: 86, dtype: float64

Valores distintos: 86

Coluna date_added

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 7077

Quantidade por categoria: date_added
2020-01-01    110
2019-11-01     91
2018-03-01     75
2019-12-31     74
2018-10-01     71
             ...
2015-12-02      1
2016-09-22      1
2016-09-17      1
2017-05-04      1
2021-09-20      1
Name: count, Length: 1713, dtype: int64

Quantidade por categoria: date_added
2020-01-01    1.251422
2019-11-01    1.035267
2018-03-01    0.853242
2019-12-31    0.841866
2018-10-01    0.807736
                ...
2015-12-02    0.011377
2016-09-22    0.011377
2016-09-17    0.011377
2017-05-04    0.011377
2021-09-20    0.011377
Name: count, Length: 1713, dtype: float64

Valores distintos: 1713

Coluna release_year

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 8716

Quantidade por categoria: release_year
2018-01-01    1146
2019-01-01    1030
2017-01-01    1030
2020-01-01     953
2016-01-01     901
              ...
1961-01-01       1
1959-01-01       1
1925-01-01       1
1966-01-01       1
1947-01-01       1
Name: count, Length: 74, dtype: int64

Quantidade por categoria: release_year
2018-01-01    13.037543
2019-01-01    11.717861
2017-01-01    11.717861
2020-01-01    10.841866
2016-01-01    10.250284
                ...
1961-01-01     0.011377
1959-01-01     0.011377
1925-01-01     0.011377
1966-01-01     0.011377
1947-01-01     0.011377
Name: count, Length: 74, dtype: float64

Valores distintos: 74

Coluna rating

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 8776

Quantidade por categoria: rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

Quantidade por categoria: rating
TV-MA       36.461889
TV-14       24.539249
TV-PG        9.795222
R            9.089875
PG-13        5.574516
TV-Y7        3.788396
TV-Y         3.481229
PG           3.265074
TV-G         2.502844
NR           0.898749
G            0.466439
TV-Y7-FV     0.068259
NC-17        0.034130
UR           0.034130
Name: count, dtype: float64

Valores distintos: 14

Coluna duration

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 8570

Quantidade por categoria: duration
1 Season      1791
2 Seasons      421
3 Seasons      198
90 min         152
94 min         146
              ...
191 min          1
17 Seasons       1
10 min           1
312 min          1
11 Seasons       1
Name: count, Length: 220, dtype: int64

Quantidade por categoria: duration
1 Season      20.375427
2 Seasons      4.789534
3 Seasons      2.252560
90 min         1.729238
94 min         1.660978
                ...
191 min        0.011377
17 Seasons     0.011377
10 min         0.011377
312 min        0.011377
11 Seasons     0.011377
Name: count, Length: 220, dtype: float64

Valores distintos: 220

Coluna listed_in

QTD Nulos: 0
% Nulos: 0.0

QTD Duplicados: 8277

Quantidade por categoria: listed_in
Dramas, International Movies                               362
Documentaries                                              359
Stand-Up Comedy                                            334
Comedies, Dramas, International Movies                     274
Dramas, Independent Movies, International Movies           252
                                                          ...
TV Action & Adventure, TV Comedies                           1
Romantic TV Shows, Spanish-Language TV Shows, TV Dramas      1
Classic & Cult TV, Kids' TV, Spanish-Language TV Shows       1
Anime Series, Crime TV Shows, TV Thrillers                   1
British TV Shows, Docuseries, Reality TV                     1
Name: count, Length: 513, dtype: int64

Quantidade por categoria: listed_in
Dramas, International Movies                               4.118316
Documentaries                                              4.084187
Stand-Up Comedy                                            3.799772
Comedies, Dramas, International Movies                     3.117179
Dramas, Independent Movies, International Movies           2.866894
                                                             ...
TV Action & Adventure, TV Comedies                         0.011377
Romantic TV Shows, Spanish-Language TV Shows, TV Dramas    0.011377
Classic & Cult TV, Kids' TV, Spanish-Language TV Shows     0.011377
Anime Series, Crime TV Shows, TV Thrillers                 0.011377
British TV Shows, Docuseries, Reality TV                   0.011377
Name: count, Length: 513, dtype: float64

Valores distintos: 513

In [138]:
df[df['title'].duplicated(keep = False )]

Empty DataFrame
Columns: [show_id, type, title, director, country, date_added, release_year, rating, duration, listed_in]
Index: []

In [137]:
df.drop_duplicates(subset = ['title'], keep= 'last', inplace = True)

In [139]:
df.drop(columns = ['director'], inplace = True)

In [140]:
df[['Listed 1', 'Listed 2', 'Listed 3']] = (
    df['listed_in']
    .str.split(',', expand=True)
    .iloc[:, :3]
)

In [141]:
df['rating'] = df['rating'].replace({'UR': 'NR'})

In [142]:
# replace — só substitui o que está no dicionário, mantém o resto
df['Métrica'] = df['Métrica'].replace({'Seasons': 'Season'})

KeyError: 'Métrica'

In [124]:
display(df)

,show_id,type,title,country,date_added,release_year,rating,duration,listed_in,Duracao Numerica,Métrica,Listed 1,Listed 2,Listed 3
0,s1,Movie,Dick Johnson Is Dead,United States,2021-09-25,2020-01-01,PG-13,90 min,Documentaries,90,min,Documentaries,None,None
1,s3,TV Show,Ganglands,France,2021-09-24,2021-01-01,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1,Season,Crime TV Shows,International TV Shows,TV Action & Adventure
2,s6,TV Show,Midnight Mass,United States,2021-09-24,2021-01-01,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",1,Season,TV Dramas,TV Horror,TV Mysteries
3,s14,Movie,Confessions of an Invisible Girl,Brazil,2021-09-22,2021-01-01,TV-PG,91 min,"Children & Family Movies, Comedies",91,min,Children & Family Movies,Comedies,None
4,s8,Movie,Sankofa,United States,2021-09-24,1993-01-01,TV-MA,125 min,"Dramas, Independent Movies, International Movies",125,min,Dramas,Independent Movies,International Movies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Turkey,2017-01-17,2016-01-01,TV-PG,2 Seasons,"International TV Shows, TV Dramas",2,Season,International TV Shows,TV Dramas,None
8786,s8798,TV Show,Zak Storm,United States,2018-09-13,2016-01-01,TV-Y7,3 Seasons,Kids' TV,3,Season,Kids' TV,None,None
8787,s8801,TV Show,Zindagi Gulzar Hai,Pakistan,2016-12-15,2012-01-01,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",1,Season,International TV Shows,Romantic TV Shows,TV Dramas
8788,s8784,TV Show,Yoko,Pakistan,2018-06-23,2016-01-01,TV-Y,1 Season,Kids' TV,1,Season,Kids' TV,None,None
8789,s8786,TV Show,YOM,Pakistan,2018-06-07,2016-01-01,TV-Y7,1 Season,Kids' TV,1,Season,Kids' TV,None,None

In [145]:
df.loc[df['date_added'] < df['release_year'], 'date_added'] = None

In [146]:
df[df['show_id'] == 's5395']

,show_id,type,title,country,date_added,release_year,rating,duration,listed_in,Listed 1,Listed 2,Listed 3
3869,s5395,Movie,Hans Teeuwen: Real Rancour,Netherlands,NaT,2018-01-01,TV-MA,86 min,Stand-Up Comedy,Stand-Up Comedy,None,None

In [143]:
df[df['date_added'] < df['release_year']]
# s5395
# s7064
# s7113

,show_id,type,title,country,date_added,release_year,rating,duration,listed_in,Listed 1,Listed 2,Listed 3
3869,s5395,Movie,Hans Teeuwen: Real Rancour,Netherlands,2017-07-01,2018-01-01,TV-MA,86 min,Stand-Up Comedy,Stand-Up Comedy,None,None
5138,s7064,Movie,Incoming,Serbia,2018-10-26,2019-01-01,TV-MA,89 min,"Action & Adventure, Sci-Fi & Fantasy",Action & Adventure,Sci-Fi & Fantasy,None
5178,s7113,TV Show,Jack Taylor,United States,2013-03-31,2016-01-01,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Crime TV Shows,International TV Shows,TV Dramas
6948,s1552,TV Show,Hilda,United Kingdom,2020-12-14,2021-01-01,TV-Y7,2 Seasons,Kids' TV,Kids' TV,None,None
6992,s1697,TV Show,Polly Pocket,Canada,2020-11-15,2021-01-01,TV-Y,2 Seasons,Kids' TV,Kids' TV,None,None
7355,s2921,TV Show,Love Is Blind,United States,2020-02-13,2021-01-01,TV-MA,1 Season,"Reality TV, Romantic TV Shows",Reality TV,Romantic TV Shows,None
7436,s3169,TV Show,Fuller House,United States,2019-12-06,2020-01-01,TV-PG,5 Seasons,TV Comedies,TV Comedies,None,None
7484,s3288,TV Show,Maradona in Mexico,Argentina,2019-11-13,2020-01-01,TV-MA,1 Season,"Docuseries, Spanish-Language TV Shows",Docuseries,Spanish-Language TV Shows,None
7517,s3370,TV Show,BoJack Horseman,United States,2019-10-25,2020-01-01,TV-MA,6 Seasons,TV Comedies,TV Comedies,None,None
7537,s3434,TV Show,The Hook Up Plan,France,2019-10-11,2020-01-01,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",International TV Shows,Romantic TV Shows,TV Comedies
7996,s4845,TV Show,Unbreakable Kimmy Schmidt,United States,2018-05-30,2019-01-01,TV-14,4 Seasons,TV Comedies,TV Comedies,None,None
7997,s4846,TV Show,Arrested Development,United States,2018-05-29,2019-01-01,TV-MA,5 Seasons,TV Comedies,TV Comedies,None,None
8223,s5659,TV Show,Sense8,United States,2016-12-23,2018-01-01,TV-MA,2 Seasons,"Crime TV Shows, TV Dramas, TV Mysteries",Crime TV Shows,TV Dramas,TV Mysteries
8235,s5678,TV Show,Tokyo Trial,Canada,2016-12-13,2017-01-01,TV-MA,1 Season,"International TV Shows, TV Dramas",International TV Shows,TV Dramas,None